INSERT INTO provincia(nombre)
VALUES 
('San José'), 
('Alajuela'), 
('Cartago'), 
('Heredia'), 
('Guanacaste'), 
('Puntarenas'), 
('Limón');

INSERT INTO canton(id_provincia, nombre)
VALUES
(1, 'San José'),
(1, 'Escazú'),
(1, 'Desamparados'),
(1, 'Puriscal'),
(1, 'Tarrazú'),
(1, 'Aserrí'),
(1, 'Mora'),
(1, 'Goicoechea'),
(1, 'Santa Ana'),
(1, 'Alajuelita'),
(1, 'Vásquez de Coronado'),
(1, 'Acosta'),
(1, 'Tibás'),
(1, 'Moravia'),
(1, 'Montes de Oca'),
(1, 'Turrubares'),
(1, 'Dota'),
(1, 'Curridabat'),
(1, 'Pérez Zeledón'),
(1, 'León Cortés'),
(2, 'Alajuela'),
(2, 'San Ramón'),
(2, 'Grecia'),
(2, 'San Mateo'),
(2, 'Atenas'),
(2, 'Naranjo'),
(2, 'Palmares'),
(2, 'Poás'),
(2, 'Orotina'),
(2, 'San Carlos'),
(2, 'Zarcero'),
(2, 'Sarchí'),
(2, 'Upala'),
(2, 'Los Chiles'),
(2, 'Guatuso'),
(2, 'Río Cuarto'),
(3, 'Cartago'),
(3, 'Paraíso'),
(3, 'La Unión'),
(3, 'Jiménez'),
(3, 'Turrialba'),
(3, 'Alvarado'),
(3, 'Oreamuno'),
(3, 'El Guarco'),
(4, 'Heredia'),
(4, 'Barva'),
(4, 'Santo Domingo'),
(4, 'Santa Bárbara'),
(4, 'San Rafael'),
(4, 'San Isidro'),
(4, 'Belén'),
(4, 'Flores'),
(4, 'San Pablo'),
(4, 'Sarapiquí'),
(5, 'Liberia'),
(5, 'Nicoya'),
(5, 'Santa Cruz'),
(5, 'Bagaces'),
(5, 'Carrillo'),
(5, 'Cañas'),
(5, 'Abangares'),
(5, 'Tilarán'),
(5, 'Nandayure'),
(5, 'La Cruz'),
(5, 'Hojancha'),
(6, 'Puntarenas'),
(6, 'Esparza'),
(6, 'Buenos Aires'),
(6, 'Montes de Oro'),
(6, 'Osa'),
(6, 'Quepos'),
(6, 'Golfito'),
(6, 'Coto Brus'),
(6, 'Parrita'),
(6, 'Corredores'),
(6, 'Garabito'),
(6, 'Monteverde'),
(6, 'Puerto Jiménez'),
(7, 'Limón'),
(7, 'Pococí'),
(7, 'Siquirres'),
(7, 'Talamanca'),
(7, 'Matina'),
(7, 'Guácimo');

INSERT INTO estado_evento(estado)
VALUES 
('Solicitado'), 
('Activo'),
('Finalizado');

INSERT INTO modalidad(modalidad, precio)
VALUES 
('Virtual', 1), 
('Presencial', 1);

INSERT INTO servicio (id, servicio, icono, precio, descripcion) VALUES
(1, 'Alimentación', 'fa-solid fa-burger', '1.00', 'Deleita tus eventos con la comida de la mejor calidad que brinda Eventor. Una amplia variedad de comidas a escoger elaboradas por profesionales y los mejores ingredientes.'),
(2, 'Entretenimiento', 'fa-solid fa-gamepad', '1.00', 'Una gran variedad de entretenimiento para tus eventos empresariales con Eventor. Transforma cualquier evento y crea buenos recuerdos.'),
(3, 'Decoración', 'fa-solid fa-umbrella-beach', '1.00', 'Toda la decoración necesaria para tu evento empresarial con Eventor.'),
(4, 'Música', 'fa-solid fa-music', '1.00', 'Gran variedad de música en vivo, desde un DJ hasta una banda. Toda la decoración auditiva para cualquier ocasión y evento empresarial con Eventor.'),
(5, 'Fotografía', 'fa-solid fa-camera', '1.00', 'Documenta tu evento empresarial y captura los mejores momentos con nuestro servicio de fotografía o video. Los mejores recuerdos de tus eventos empresariales los capturas con Eventor.');

INSERT INTO tipo_evento (id, tipo_evento, icono, precio, descripcion) VALUES
(1, 'Cenas', 'fa-solid fa-utensils', '1.00', 'Organiza tus cenas empresariales más rápido que nunca y sin preocuparte por los detalles. Estrecha relaciones con clientes o celebra con las mejores cenas con Eventor.'),
(2, 'Fiestas', 'fa-solid fa-gift', '1.00', 'Las mejores fiestas empresariales con Eventor. Organiza tus fiestas fácilmente y celebra a lo grande los triunfos de tu empresa.'),
(3, 'Aniversarios', 'fa-solid fa-cake-candles', '1.00', 'Celebra el aniversario de  tu empresa de la mejor maneja. Organización de los mejores aniversarios con Eventor.'),
(4, 'Capacitaciones', 'fa-solid fa-chalkboard-user', '1.00', 'Capacitaciones con los mejores en la materia. Organización de capacitaciones para tu empresa con Eventor.'),
(5, 'Congresos', 'fa-solid fa-person-chalkboard', '1.00', 'Organiza todo tipo de congresos con Eventor. Brinda a tu empresa los conocimeintos y habilidades necesarias para el trinfo.'),
(6, 'Convenciones', 'fa-solid fa-people-group', '1.00', 'Eventor ofrece la organización de las mejores convenciones empresariales. Crea la mejor convención para tu empresa con Eventor.'),
(7, 'Actividades deportivas', 'fa-solid fa-futbol', '1.00', 'Torneos de fútbol, baseball, basquetball y muchos otros deportes. Organiza los mejores eventos deportivos empresariales con Eventor.'),
(8, 'Actividades familiares', 'fa-solid fa-house-chimney-window', '1.00', 'Picnics, juegos recreativos y muchas actividades más en familia. Refuerza los lazos de tu empresa con las mejores actividades familiares organizadas por Eventor');